version: 2
jobs:
  build:
    branches:
      only:
        - master
        - maint
    docker:
      - image: condaforge/linux-anvil
    steps:
      - checkout
      - run: .circleci/test-package python=2.7 MPI=mpich
      - run: .circleci/test-package python=3.4 MPI=mpich
      - run: .circleci/test-package python=3.5 MPI=mpich
      - run: .circleci/test-package python=3.6 MPI=mpich
      - run: .circleci/test-package python=3.7 MPI=mpich
      - run: .circleci/test-package python=2.7 MPI=openmpi
      - run: .circleci/test-package python=3.4 MPI=openmpi
      - run: .circleci/test-package python=3.5 MPI=openmpi
      - run: .circleci/test-package python=3.6 MPI=openmpi
      - run: .circleci/test-package python=3.7 MPI=openmpi
      - run: .circleci/upload-coverage
